//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_tickets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusdbEntities : DbContext
    {
        public BusdbEntities()
            : base("name=BusdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<passenger> passengers { get; set; }
        public virtual DbSet<rbschedule> rbschedules { get; set; }
        public virtual DbSet<reserve> reserves { get; set; }
        public virtual DbSet<route> routes { get; set; }
    }
}
