//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rbschedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rbschedule()
        {
            this.reserves = new HashSet<reserve>();
        }
    
        public int sid { get; set; }
        public int rid { get; set; }
        public int bid { get; set; }
        public int fare { get; set; }
        public System.DateTime departure_date { get; set; }
        public System.TimeSpan departure_time { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual route route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserve> reserves { get; set; }
    }
}
