//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve
    {
        public int ticket_no { get; set; }
        public int rid { get; set; }
        public int pid { get; set; }
        public string name { get; set; }
        public string phone_no { get; set; }
        public string gender { get; set; }
        public int sid { get; set; }
        public string email { get; set; }
        public string seat_no { get; set; }
    
        public virtual passenger passenger { get; set; }
        public virtual rbschedule rbschedule { get; set; }
        public virtual reserve reserves1 { get; set; }
        public virtual reserve reserve1 { get; set; }
        public virtual route route { get; set; }
    }
}
